# Scratch Org Definition File
SCRATCH_DEF: config/project-scratch-def.json

# Default duration in days
DURATION: 10

# Default Devhub
DEVHUB: my-dev-hub-org

# use_namepspace
USE_NAMESPACE: False

# List of managed package Ids to install into the Org.
PACKAGE_IDS: []

# List of managed package permission sets to assign to the user.
PACKAGE_P_SETS: []

# Pre-Deploy use if metadata deploy sequence is important.
PRE_DEPLOY: []

# List of metadata source folders (SRC_FOLDERS = ["force-app"])
SRC_FOLDERS: []

# List of permission sets to assign to the user.
P_SETS: []

# Anonymous APEX files to execute ("setupdata.apex")
BUILD_DATA_CMD: []

# Name of template to use to create the community
TMPLT_NAME:

# Name of the Lightning community that you want to publish.
SITE_NAME:

# Post-Deploy use if metadata deploy sequence is important.
POST_DEPLOY: []
